### ISSUE TITLE
RuntimeError related to pyfftw

### ISSUE THREAD

**Issue by minkyu-p** [wannier-berri/wannier-berri#123]
After I reinstall anaconda and wannierberri (version 0.11.1), I encountered the following error. 

```
Traceback (most recent call last):
  File "/home/user3/minkyu/computations/Fe/pbe-spn-kjpaw/wannier/berry/wberri.py", line 18, in <module>
    system=wberri.System_w90(seedname='../wannier',berry=True,spin=False,morb=False,use_ws=True)
  File "/home/user3/minkyu/anaconda3/lib/python3.9/site-packages/wannierberri/__system_w90.py", line 89, in __init__
    self.Ham_R=fourier_q_to_R_loc( HHq )
  File "/home/user3/minkyu/anaconda3/lib/python3.9/site-packages/wannierberri/__utility.py", line 295, in fourier_q_to_R
    AA_q_mp = FFT(AA_q_mp,axes=(0,1,2),numthreads=numthreads,fft=fft,destroy=False)
  File "/home/user3/minkyu/anaconda3/lib/python3.9/site-packages/wannierberri/__utility.py", line 281, in FFT
    return fft_W(inp,axes,inverse=inverse,destroy=destroy,numthreads=numthreads)
  File "/home/user3/minkyu/anaconda3/lib/python3.9/site-packages/wannierberri/__utility.py", line 251, in fft_W
    fft_object = pyfftw.FFTW(fft_in, fft_out,axes=axes, 
  File "pyfftw/pyfftw.pyx", line 1426, in pyfftw.pyfftw.FFTW.__cinit__
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.
```

The problem can be temporarily solved by setting `fftlib='numpy'` in `Data_K.py` and `fft='numpy'` in `__system_w90.py`.

By the way, happy new year!

**Comment by stepan-tsirkin** [comment]
Happy New Year, @minkyu-p !

This issue is known  :  #114  and related to conflict between python 3.9 and pyfftw. 
Another workaround is suggested by @jaemolihm : https://github.com/wannier-berri/wannier-berri/issues/114#issuecomment-991616333

Long ago be ause of other problems with `pyFFTW` the following lines were added:

https://github.com/wannier-berri/wannier-berri/blob/82b809ea7cf8fdedf6e411a61fa15b3ae0cf91d1/wannierberri/__utility.py#L26-L31

i.e. if `pyfftw` was not installed, wannierberri will use numpy everywhere.

We may consider setting `numpy` as default and remove pyfftw from dependencies (so that user needs to have it install manually if there is a wish to use it). In my practice, the advantage of `pyfftw` over `numpy` is not much (if any).

**Comment by minkyu-p** [comment]
Thank you @stepan-tsirkin !

I see.
I have no strong reason to use python 3.9, so I can use python 3.8.

**Comment by jaemolihm** [comment]
I checked that all tests pass in python 3.9.7 (with pyFFTW-0.13.0). Please reopen issue #114 (not this one) if you still have the same problem.
