### ISSUE TITLE
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug

### ISSUE THREAD

**Issue by ChenqiangHua** [wannier-berri/wannier-berri#242]
Thanks first!
Dears,
 i met a problem when test a case for Berry curvature using sea and surface two methods.
it is a 2D system, so i set the grid in a 2D way.     
can anyone help me with this to find where/what is wrong?
the printed lines are attached below.                 the input is also attached below.

%%%%%%%%%%%%%%%%%%%%%%%
tb.dat was read successfully.
%%%%%%%%%%%%%%%%
then it writes:
Berry curvature dipole (dimensionless)
XXXXX
Berry curvature dipole (dimensionless)
XXXXXX
Density of states
etermining grids from NK=[20, 20, 1] (<class 'list'>), NKdiv=None (<class 'NoneType'>), NKFFT=[5, 5, 1] (<class 'NoneType'>)
The grids were set to NKdiv=[4 4 1], NKFFT=[5 5 1], NKtot=[20 20  1]
Grid is regular
The set of k points is a Grid() with NKdiv=[4 4 1], NKFFT=[5 5 1], NKtot=[20 20  1]
generating K_list
Done in 0.0006620883941650391 s 
excluding symmetry-equivalent K-points from initial grid
Done in 0.002835512161254883 s 
Done in 0.0029077529907226562 s 
K_list contains 16 Irreducible points(100.0%) out of initial 4x4x1=16 grid
Done, sum of weights:1.0
symgroup : <wannierberri.symmetry.Group object at 0x7f17cfc7adc0>
processing 16 K points : using  4 processes.
# K-points calculated  Wall time (sec)  Est. remaining (sec)
                   4              5.4                  16.2
                   8              5.4                   5.4
                  12              5.4                   1.8
%%%%%%%%%%%%%%%%%%%%
**Then   error happens!**

  File "/beegfs/home/b00004/calculation-hcq/inv/soc/w901.2/wberri.py", line 74, in <module>
    result = wberri.run(
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/wannierberri/run.py", line 254, in run
    counter += process(
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/wannierberri/run.py", line 76, in process
    res = parallel.ray.get(remotes)
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/ray/_private/worker.py", line 2280, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::paralfunc() (pid=17441, ip=192.168.252.4)
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/wannierberri/run.py", line 190, in paralfunc
    data = Data_K(_system, Kpoint.Kp_fullBZ, grid=_grid, Kpoint=Kpoint, **parameters_K)
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/wannierberri/data_K.py", line 110, in __init__
    self.fft_R_to_k = FFT_R_to_k(
  File "/beegfs/home/b00004/anaconda3/lib/python3.9/site-packages/wannierberri/__utility.py", line 175, in __init__
    self.fft_plan = pyfftw.FFTW(
  File "pyfftw/pyfftw.pyx", line 1426, in pyfftw.pyfftw.FFTW.__cinit__
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.

%%%%%%%%%%%%%%%%%%%%%%%%%
**below is the input:**

parallel = wberri.Parallel(num_cpus=4)
system=wberri.System_tb('wannier90_tb.dat',berry=True)
from wannierberri.smoother import FermiDiracSmoother
efermi = np.linspace(-5, 2.0, 201, True)
kwargs = dict(
    Efermi=efermi,
    kwargs_formula={"external_terms": False},
    smoother=FermiDiracSmoother(efermi, T_Kelvin=20, maxdE=8)
)
calculators = {
    'berry_dipole_fermi_sea': calc.static.BerryDipole_FermiSea(**kwargs),
    'berry_dipole_fermi_surface': calc.static.BerryDipole_FermiSurf(**kwargs),
    'dos': calc.static.DOS(Efermi=efermi,),
}
grid = wberri.Grid(system, NK=([20, 20, 1]), NKFFT=([5, 5, 1 ])	)
result = wberri.run(
    system,
    grid=grid,
    calculators=calculators,
    parallel=parallel,
    print_Kpoints = False,
)
data_fsurf = result.results['berry_dipole_fermi_surface'].data
data_fsea = result.results['berry_dipole_fermi_sea'].data

.... then the plot part.

**Comment by Liu-Xiaoxiong** [comment]
Hi, 

I could you please try to use 
parallel = wberri.Serial(). I think it will run.

Recently I found we have some problem with Ray to parallel. 
I am sorry for that. We will find the bug and fix it soon.

Xiaoxiong Liu

**Comment by stepan-tsirkin** [comment]
Hi @ChenqiangHua ,

according to the traceback, the error is raised by the `pyfftw` library, and it seems to be a bug on their side, probably introduced in recent versions. Recently we also noticed this happening on some computers.  Try switching to the `numpy` library for fft via 

`wberri.run(...  , parameters_K = dict( fftlib =  "numpy" ) )`

That should work, maybe a bit slower, but not too much. 

See documentation pages for reference:
https://wannier-berri.org/docs/run.html#wannierberri.run
https://wannier-berri.org/docs/data_K.html

**Comment by ChenqiangHua** [comment]
> Hi,
> 
> I could you please try to use parallel = wberri.Serial(). I think it will run.
> 
> Recently I found we have some problem with Ray to parallel. I am sorry for that. We will find the bug and fix it soon.
> 
> Xiaoxiong Liu

Hi iaoxiong Liu,
Thnaks for your quick reply!   I have tried this 'Serial' and the same bug apper.

**Comment by ChenqiangHua** [comment]
> Hi @ChenqiangHua ,
> 
> according to the traceback, the error is raised by the `pyfftw` library, and it seems to be a bug on their side, probably introduced in recent versions. Recently we also noticed this happening on some computers. Try switching to the `numpy` library for fft via
> 
> `wberri.run(... , parameters_K = dict( fftlib = "numpy" ) )`
> 
> That should work, maybe a bit slower, but not too much.
> 
> See documentation pages for reference: https://wannier-berri.org/docs/run.html#wannierberri.run https://wannier-berri.org/docs/data_K.html


Dear, 
Thanks for the quick reply!   do you mean this
add the tage in the wberri.run()  and keep others?

%%%%%%%%%%%%%%
grid = wberri.Grid(system, NK=([20, 20, 1]), NKFFT=([5, 5, 1 ]) )
result = wberri.run(
system,
grid=grid,
calculators=calculators,
parallel=parallel,
print_Kpoints = False,


parameters_K = dict( fftlib = "numpy" ) 
)


Thanks!
Chenqiang Hua

**Comment by stepan-tsirkin** [comment]
> Dear, Thanks for the quick reply! do you mean this add the tage in the wberri.run() and keep others?
> 
> %%%%%%%%%%%%%% 
> grid = wberri.Grid(system, NK=([20, 20, 1]), NKFFT=([5, 5, 1 ]) ) 
> result = wberri.run( system, grid=grid, calculators=calculators, parallel=parallel, print_Kpoints = False,
> parameters_K = dict( fftlib = "numpy" ) )

Exaactly!

**Comment by Vahid999** [comment]
Hi,

I am getting the same error when I use the following input:

import wannierberri as wberri
import pyfftw 
import numpy as np
system=wberri.System_w90('wannier90',berry=True)
grid=wberri.Grid(system,length=20)
parallel=None
wberri.tabulate(system, grid,
             quantities=["berry"],
             frmsf_name="Mn3Ge",
             parallel = None,
             parameters_K = dict( fftlib = "numpy" ),
             ibands=np.arange(117,121),
             Ef0=11.8795)

The files wannier90.amn, wannier90.mmn, wannier90.chk and wannier90.eig exist in the working directory. the routine puffer is imported before numpy and the parameters_K line is added. 

The error is:

`using fortio to read
Reading restart information from file wannier90.chk :
Time to read .chk : 2.427590847015381
Time for MMN.__init__() : 388.829931974411 , read : 384.0323712825775 , headstring 4.797560691833496
Traceback (most recent call last):
  File "/scratch/vaskarpo/Mn2G3/vasp_impi/noU/hexagonal/bandstructure/wannier/new/final2/wannierberri/berry.py", line 5, in <module>
    system=wberri.System_w90('wannier90',berry=True)
  File "/home/vaskarpo/bin/wannierberri/lib/python3.10/site-packages/wannierberri/system/system_w90.py", line 101, in __init__
    self.set_R_mat('Ham', fourier_q_to_R_loc(HHq))
  File "/home/vaskarpo/bin/wannierberri/lib/python3.10/site-packages/wannierberri/__utility.py", line 155, in fourier_q_to_R
    AA_q_mp = FFT(AA_q_mp, axes=(0, 1, 2), numthreads=numthreads, fft=fft, destroy=False)
  File "/home/vaskarpo/bin/wannierberri/lib/python3.10/site-packages/wannierberri/__utility.py", line 141, in FFT
    return fft_W(inp, axes, inverse=inverse, destroy=destroy, numthreads=numthreads)
  File "/home/vaskarpo/bin/wannierberri/lib/python3.10/site-packages/wannierberri/__utility.py", line 110, in fft_W
    fft_object = pyfftw.FFTW(
  File "pyfftw/pyfftw.pyx", line 1426, in pyfftw.pyfftw.FFTW.__cinit__
RuntimeError: The data has an uncaught error that led to the planner returning NULL. This is a bug.`

I would appreciate any suggestions.

Thanks,
Vahid

**Comment by stepan-tsirkin** [comment]
@Vahid999 

To avoid using `pyfftw` try this line (see [docs](https://docs.wannier-berri.org/en/master/docs/system.html#id3) ) :  

```
system=wberri.System_w90('wannier90', berry=True, fft='numpy')
```

This is a bug in `pyfftw` which happens on some installations. You may also try to install an older [version](https://pypi.org/project/pyFFTW/#history) of pyfftw, and inform us if it helps. Because this error had not been reported before their latest release of Jan 2023.

**Comment by Vahid999** [comment]
Yes, that worked. I also had to remove the line “parallel=parallel”.

Thank you for your help.

Vahid

On Nov 13, 2023, at 5:47 AM, Stepan Tsirkin ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


@Vahid999<https://github.com/Vahid999>

To avoid using pyfftw try this line (see docs<https://docs.wannier-berri.org/en/master/docs/system.html#id3> ) :

system=wberri.System_w90('wannier90', berry=True, fft='numpy')


This is a bug in pyfftw which happens on some installations. You may also try to install an older version<https://pypi.org/project/pyFFTW/#history> of pyfftw, and inform us if it helps. Because this error had not been reported before their latest release of Jan 2023.

**Comment by stepan-tsirkin** [comment]
> Yes, that worked. I also had to remove the line “parallel=parallel”. 

Well, this means you do not have any parallelization, only serial execution. But if you are fine with that, it is ok

Note, that `integrate()` and `tabulate()` functions are obsolete and will be removed in next release.  It is recommended to use `run()` with proper calculators, see [tutorial](https://tutorial.wannier-berri.org/tutorials/1_basic/tutorial-wb-basic-solution.html#Calaculation-on-a-3D-grid)
