### ISSUE TITLE
How can I obtain the Berry curvature varying with k-points in reciprocal space, rather than in the femsf format?

### ISSUE THREAD

**Issue by physicswangsy** [wannier-berri/wannier-berri#323]

**Comment by stepan-tsirkin** [comment]
You may get the data as NumPy arrays:, see [tutorial](https://tutorial.wannier-berri.org/tutorials/1_basic/tutorial-wb-basic-solution.html#Analyze-the-tabulated-data)

```
Energy = grid_result.get_data(iband=5, quantity='Energy')
berry  = grid_result.get_data(iband=5, quantity='berry',component='z')
```

**Comment by physicswangsy** [comment]
Can you provide me with a complete input file example? I want to use Python to plot such a graph
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4461786218677026692 skey=@crypt_53132df7_bc44ce4124fa670ac50a308726cb75e9 mmweb_appid=wx_webfilehelper](https://github.com/wannier-berri/wannier-berri/assets/167171507/9cebeb83-4d2e-4889-8be7-e986cbcce822)

**Comment by physicswangsy** [comment]
First of all, thank you for your help, but I encountered the following error when running the code according to your advice.The error is as follows：{'tabulate': <wannierberri.result.__tabresult.TABresult object at 0x7ff350eb0a90>}
Traceback (most recent call last):
  File "script2", line 25, in <module>
    Energy = grid_result.get_data(iband=34, quantity='Energy')
  File "/home/Wangshuaiyu/anaconda3/lib/python3.7/site-packages/wannierberri/result/__tabresult.py", line 142, in get_data
    return self.__get_data_grid(quantity, iband, component=component, efermi=efermi)
  File "/home/Wangshuaiyu/anaconda3/lib/python3.7/site-packages/wannierberri/result/__tabresult.py", line 124, in __get_data_grid
    return self.Enk.data[:, iband].reshape(self.grid)
IndexError: index 34 is out of bounds for axis 1 with size 1
The following is my input file：
system=wberri.System_w90('wannier90',berry=True)
grid = wberri.Grid(system, length=50 )   # length [ Ang] ~= 2*pi/dk
#grid = wberri.Grid(system, NK=[24,24,24], NKFFT=4)
#grid = wberri.Grid(system, NKdiv=6, NKFFT=4)


tabulators = { "Energy": wberri.calculators.tabulate.Energy(),
               "berry" : wberri.calculators.tabulate.BerryCurvature(),
             }

tab_all_grid = wberri.calculators.TabulatorAll(
                    tabulators,
                    ibands = np.arange(34,35),
                    mode = "grid"
                        )
result=wberri.run(system,
                  grid=grid,
                  calculators = {"tabulate" : tab_all_grid},
                  parallel = parallel,
                  print_Kpoints = True)

print (result.results)
grid_result = result.results["tabulate"]
Energy = grid_result.get_data(iband=ibands, quantity='Energy')
berry  = grid_result.get_data(iband=ibands, quantity='berry',component='z')
print(berry.shape,Energy.shape)

**Comment by stepan-tsirkin** [comment]
in the `TabulatorAll` you specify `ibands = np.arange(34,35)`, so all the other bands are "forgotten".  Therefore the indexing starts with zero again, so in line 
```
Energy = grid_result.get_data(iband=.., quantity='Energy')
```
iband should be`0` or `1`
