### ISSUE TITLE
Cannit allocate memory for superlarge system

### ISSUE THREAD

**Issue by sougataphy** [wannier-berri/wannier-berri#333]
Dear developers,

Thank you for the nice WannierBerri code. Though I am new to the Wannierberri, until now, it has been beneficial to my research. 

Recently, I have been working on a super large system with 1008 wannier functions and 84 atoms. I used Wannierberri to calculate AHC, Ohomic conductivity, etc., which works fine when building the system with system_tb. However, now I need to calculate the orbital magnetization. As I understand, system_tb will not work in this case, and I have to use system_w90 to read the uHu file. But every time I face the '[Errno 12] Cannot allocate memory' while reading the wannier files.  I have tried different approaches, reducing to one processor per node, reducing the NKdiv(to 1), NKFFT but no help.

I tried using wannierberri.utils.cluster to build the job script, but no improvement. 

Please suggest a way to overcome the issue. I have attached all related files. Thank you very much for your help.

[morb_0605-155643.log](https://github.com/user-attachments/files/15597219/morb_0605-155643.log)
[auto_script.sh.txt](https://github.com/user-attachments/files/15597231/auto_script.sh.txt)
[job_knl_normal.sh.txt](https://github.com/user-attachments/files/15597232/job_knl_normal.sh.txt)
[morb_0605-155643.sh.txt](https://github.com/user-attachments/files/15597233/morb_0605-155643.sh.txt)
[Morb.py.txt](https://github.com/user-attachments/files/15597234/Morb.py.txt)
[myjob.e583080.txt](https://github.com/user-attachments/files/15597235/myjob.e583080.txt)
[myjob.o583080.txt](https://github.com/user-attachments/files/15597236/myjob.o583080.txt)

**Comment by sougataphy** [comment]
I further checked for a different system with a less wannier function (216). The error is present. So I guess the problem is not the system size but machine-related.

**Comment by stepan-tsirkin** [comment]
Wow, 1000 WFs is a lot, I never went above 200, so I am happy that it works at least with _tb file. 

So, the System_w90 does not work for any system on your machine (say, even for the BCC Fe example with 18 WFs and 4^3 k-points), or is there some threshold between what is working and what is not?

**Comment by sougataphy** [comment]
Hi Stephan, thank you very much for the reply. Yes, It works fine for the Fe example. 

Regards
Sougata Mardanya

**Comment by sougataphy** [comment]
The files are pretty big; here is the list, even if the code can get the.mmn, I doubt the uHu will be even more challenging. 

5.2G	wannier90.amn
6.4M	wannier90_band.dat
512	wannier90_band.gnu
8.5K	wannier90_band.kpt
512	wannier90_band.labelinfo.dat
60K	wannier90_centres.xyz
12G	wannier90.chk
4.7M	wannier90.eig
6.4G	wannier90_hr.dat
26G	wannier90.mmn
512	wannier90.node_00000.werr
20G	wannier90_tb.dat
66G	wannier90.uHu
10K	wannier90.win
193K	wannier90.wout
21K	wannier90.wpout
6.2G	wannier90_wsvec.dat

Before going to the mmn reading check, here is a list of systems with different numbers of wannier functions and the ability to read via System_W90. I have run this test in the serial setting. 

num_wann.    code   success/fail
50.                  QE      success
112.                 VASP  success
144.                VASP  success
216.                VASP  fail
1008.              VASP  fail

I tried to run the mmn read command

import wannierberri
mmn = wannierberri.system.w90_files.MMN("seedname", read_npz=True, write_npz=True, npar=0)

but I got the error stating keyword error
TypeError: __init__() got an unexpected keyword argument 'read_npz'
TypeError: __init__() got an unexpected keyword argument 'write_npz'

So I remove those and rerun with npar = 0, that leads to another error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home1/08952/tg882518/.local/lib/python3.9/site-packages/wannierberri/system/w90_files.py", line 443, in __init__
    for j in range(0, NNB * NK, npar * mult):
ValueError: range() arg 3 must not be zero

So I changed npar == 1, and it ran fine for the system with 50 wannier function. 

For the 1008 wannier function system, there is no memory error yet. It is still running. My development queue time limit is 2hr, So I will wait and see if it is working. 

if it works, then I have to think about those keyword error, and submit a job.

Thanks and regards
Sougata

**Comment by stepan-tsirkin** [comment]
the keyword errors indicate that you are using an older version. Try the latest 0.17.0

**Comment by sougataphy** [comment]
Sure, I will reduce the K-points as well. Right now, it is 2 9 5.

Modifying the grid will be an excellent option. I will try it and keep you updated.

Sougata

**Comment by sougataphy** [comment]
Hi, Stepan. The shift code worked. I can get the shifted grid. I am now calculating physical properties like AHC to get a better understanding. I will keep you updated. As you suggested, below is the modification I have done in the __grid.py

85     def __init__(self, system, length=None, NKdiv=None, NKFFT=None, NK=None, length_FFT=None, shift_k=None, use_symmetry=True):
 86
 87         super().__init__(system=system, use_symmetry=use_symmetry)
 88         NKFFT_recommended = np.array(system.NKFFT_recommended)
 89         self.div, self.FFT = determineNK(
 90             system.periodic, NKdiv, NKFFT, NK, NKFFT_recommended, self.symgroup, length=length, length_FFT=length_FFT)
 91         self.shift_k = shift_k

and 

104     def get_K_list(self, use_symmetry=True):
105         """ returns the list of Symmetry-irreducible K-points"""
106         dK = 1. / self.div
107         factor = 1. / np.prod(self.div)
108         print("generating K_list")
109         t00 = time()
110         K_list = [
111             [
112                 [
113                     KpointBZparallel(
114                         K=np.array([x, y, z]) * dK + self.shift_k*self.FFT,

**Comment by sougataphy** [comment]
Hi, I notice another thing. Maybe this is a problem with the Vasptowannier routine. The wannier centers are different for vasp544 and vasp632. First of all the orbital order for up and down spin is different. Second in vasp 6.3.2 it seems that the centers are randomly shifted to next cell. Please see the centers for a quasi 2D system  obtained from vasp544(with patch) and vasp632

vasp 632
X          0.98635043       0.98635548     -12.49989577
X          0.98635113       0.98634627     -12.46986081
X          0.98629436       0.98635361     -12.52751058
X          0.98639201       0.98636543     -12.55268128
X          0.98632086       0.98630766     -12.52755621
X          0.98635572       0.98636302     -12.55262147
X          0.98634646       0.98633302     -12.54886516
X          0.98637816       0.98635309     -12.55295061
X          0.98634375       0.98634354     -12.67326658
X          0.98634222       0.98635245     -12.70480131
X          0.98634969       0.98634953     -12.74667431
X          0.98635000       0.98634992     -12.74722571
X          0.98635013       0.98635020     -12.74236247
X          0.98634896       0.98634983     -12.73637482
X          0.98635026       0.98634962     -12.74235948
X          0.98634932       0.98635027     -12.73637782
X          0.98634965       0.98634942     -12.74307501
X          0.98635013       0.98635064     -12.74148254
X          0.98635088       0.98634901     -12.73496678
X          0.98635027       0.98635047     -12.73393515
X          0.98635028       0.98634989     -12.73473766
X          0.98634938       0.98634867     -12.73340626
X          0.98634891       0.98634958     -12.73473916
X          0.98635203       0.98634982     -12.73340618
X         -0.98635511      -0.98635185      12.46986501
X         -0.98635439      -0.98634596      12.49990455
X         -0.98634072      -0.98634150      12.55263924
X         -0.98636053      -0.98635957      12.52750119
X         -0.98637263      -0.98633894      12.55268424
X         -0.98636635      -0.98637141      12.52750038
X         -0.98631485      -0.98640694      12.55298270
X         -0.98629668      -0.98632902      12.54886757
X         -0.98636063      -0.98635854      12.70480579
X         -0.98635792      -0.98635395      12.67327803
X         -0.98635059      -0.98635122      12.74722456
X         -0.98634895      -0.98635061      12.74667350
X         -0.98635079      -0.98634998      12.73637940
X         -0.98635001      -0.98634993      12.74236200
X         -0.98635037      -0.98634924      12.73637454
X         -0.98634991      -0.98635047      12.74236131
X         -0.98634991      -0.98634962      12.74148161
X         -0.98635171      -0.98635129      12.74307343
X         -0.98634916      -0.98635012      12.73393427
X         -0.98634935      -0.98634957      12.73496677
X         -0.98635234      -0.98635134      12.73340658
X         -0.98635158      -0.98634998      12.73473788
X         -0.98634915      -0.98634916      12.73340715
X         -0.98635051      -0.98635036      12.73473831
X         -0.98635017      -0.98634831     -11.08232679
X         -0.98635046      -0.98634970     -11.08023873
X         -0.98636911      -0.98635905     -11.23417857
X         -0.98634194      -0.98634600     -11.22933677
X         -0.98636817      -0.98636030     -11.23417890
X         -0.98634913      -0.98634003     -11.22932705
X          0.98634834       0.98635100      11.08024244
X          0.98634846       0.98634834      11.08232641
X          0.98634658       0.98635775      11.22933534
X          0.98634834       0.98634237      11.23417325
X          0.98633745       0.98635422      11.22934458
X          0.98633970       0.98634637      11.23418126
X         -0.98635035       0.98634435      14.02445533
X         -0.98634899       0.98635072      14.02174205
X         -0.98635465       0.98634675      14.08585204
X         -0.98634630       0.98635098      14.07867436
X         -0.98635013       0.98634518      13.96753116
X         -0.98635028       0.98634305      13.96033925
X          0.98634830      -0.98634889      14.02445779
X          0.98634821      -0.98635239      14.02174953
X          0.98635313      -0.98635365      13.96751998
X          0.98635243      -0.98634972      13.96034727
X          0.98635093      -0.98635536      14.08584853
X          0.98635073      -0.98635607      14.07868806

From vasp544
X          0.98634706       0.98635102      15.55573674
X          0.98630153       0.98635275      15.50989927
X          0.98632630       0.98631355      15.50986187
X          0.98634653       0.98633360      15.47343602
X          0.98634476       0.98634423      15.36097562
X          0.98634996       0.98635014      15.30338092
X          0.98634983       0.98635013      15.31257179
X          0.98635035       0.98634954      15.31257203
X          0.98634915       0.98634982      15.31377409
X          0.98634998       0.98634946      15.31139513
X          0.98635029       0.98634968      15.31252244
X          0.98634914       0.98634997      15.31252122
X          2.95904605       2.95904991      12.46664698
X          2.95906306       2.95905472      12.55912402
X          2.95902920       2.95905624      12.55916964
X          2.95908406       2.95900086      12.57532120
X          2.95904151       2.95904106      12.71373829
X          2.95905001       2.95904897      12.74303729
X          2.95904956       2.95905009      12.72979209
X          2.95904955       2.95905048      12.72978920
X          2.95904972       2.95905047      12.73131512
X          2.95905050       2.95904988      12.73386048
X          2.95904885       2.95904844      12.73234306
X          2.95905067       2.95905022      12.73234359
X          2.95904963       2.95905120      16.96461539
X          2.95902873       2.95903622      16.79178582
X          2.95902908       2.95903640      16.79178653
X          0.98634812       0.98635028      11.07744004
X          0.98634840       0.98635624      11.24727641
X          0.98633743       0.98635061      11.24728807
X          2.95905034       0.98634432      14.02582021
X          2.95904464       0.98634609      14.08844302
X          2.95905094       0.98634662      13.96625445
X          0.98634830       2.95905165      14.02582044
X          0.98635419       2.95904572      13.96624275
X          0.98635136       2.95904385      14.08843938
X          0.98635393       0.98634566      15.57955958
X          0.98638667       0.98636203      15.48703137
X          0.98635405       0.98635826      15.48708311
X          0.98637705       0.98635184      15.47090655
X          0.98634247       0.98635295      15.33246616
X          0.98634985       0.98634990      15.30316176
X          0.98634996       0.98634958      15.31641028
X          0.98634960       0.98635024      15.31640902
X          0.98634954       0.98635024      15.31488449
X          0.98635024       0.98635058      15.31233860
X          0.98635052       0.98634873      15.31385696
X          0.98635165       0.98634989      15.31385678
X          2.95904461       2.95905493      12.49047018
X          2.95903886       2.95904261      12.53628889
X          2.95903450       2.95903097      12.53629200
X          2.95909841       2.95906883      12.57276604
X          2.95904112       2.95904665      12.68523488
X          2.95905049       2.95904986      12.74281864
X          2.95904986       2.95905018      12.73362798
X          2.95905035       2.95905000      12.73362789
X          2.95904822       2.95904876      12.73242436
X          2.95905005       2.95905021      12.73480488
X          2.95904998       2.95905012      12.73367758
X          2.95904951       2.95904996      12.73367798
X          2.95905012       2.95905068      16.96876195
X          2.95905929       2.95905175      16.79892122
X          2.95905076       2.95906021      16.79893041
X          0.98634837       0.98634860      11.08158613
X          0.98634928       0.98634289      11.25440634
X          0.98633854       0.98634704      11.25441650
X          2.95905148       0.98635027      14.02037970
X          2.95905289       0.98635075      14.07995104
X          2.95905028       0.98634241      13.95774857
X          0.98634796       2.95904787      14.02038376
X          0.98635165       2.95905014      13.95775472
X          0.98635133       2.95904445      14.07996339


The 544 seeems to agree with the location of atom position.


Does this change affect any calculation?

**Comment by stepan-tsirkin** [comment]
The order of spins was discussed in #338 

The jump to the other unit cell may have some effect, if you do not use translational-invariant position matrix elements :

https://github.com/wannier-berri/wannier-berri/blob/3f0d8a0c5f1d88445d5bb63c6dcdb7ad67378348/wannierberri/system/system_w90.py#L39-L42

This is a recent development, not yet well documented/tested. 

But in general for 2D systems with Wannier, it is wore recommended to put the center of the layer at the origin of the unit cell. (and accordingly specify atomic position at +- z values around zero.) also guiding_centers in Wannier90 may help.

**Comment by sougataphy** [comment]
Okay. Thanks a lot. 

 In my case the layer center is at the unit cell center but not written in +,- format. 

Also for bulk I guess it will not have any effect.

**Comment by sjhong6230** [comment]
> Also for bulk I guess it will not have any effect.

This is generally not true. The non-translation-invariant finite difference formula used in evaluating the position matrix elements works well only if the Wannier functions are near the origin of the Born-von Karman supercell defined by the coarse _ab initio_ grid. In this context, a larger magnitude of the coordinate implies Wannier functions far from the origin of the supercell and a poorer approximation quality.

For example, moving the crystal coordinate of Fe in bcc Fe from (0.0, 0.0, 0.0) to (0.5, 0.5, 0.5) does not affect the DFT computations. However, the same modification in Wannier90 will affect the quality of the results if the coarse grid is not fine enough.

**Comment by sougataphy** [comment]
Thank you for the comment. 

by 'larger magnitude of the coordinate' do you refer to the wannier function spread?

**Comment by sjhong6230** [comment]
> by 'larger magnitude of the coordinate' do you refer to the wannier function spread?

No. I meant the absolute value of the coordinate of the Wannier centers.

**Comment by sougataphy** [comment]
okay I understand. Thank you very much.
