### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by shmr69** [wannier-berri/wannier-berri#368]
Hi, I'm trying to install wannierberri (1.0.2) using pip (python 3.9.9, running on Rocky Linux 8.10 (Green Obsidian)) which seems to work fine, but when I try to import it in my python script, I get this error:

> Traceback (most recent call last):
>   File "/nobackup/shmr69/BaTiO3/relax_GW/wannier/include_Ba_f/freeze_bands/symmetriseWF.py", line 8, in <module>
>     import wannierberri
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/__init__.py", line 27, in <module>
>     from .run import run
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/run.py", line 22, in <module>
>     from .data_K import get_data_k
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/data_K.py", line 18, in <module>
>     from .system.system import System
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/system/__init__.py", line 16, in <module>
>     from .system_w90 import System_w90
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/system/system_w90.py", line 22, in <module>
>     from ..w90files import Wannier90data
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/w90files/__init__.py", line 6, in <module>
>     from .dmn import DMN
>   File "/home/shmr69/.local/lib/python3.9/site-packages/wannierberri/w90files/dmn.py", line 3, in <module>
>     from irrep.bandstructure import BandStructure
>   File "/home/shmr69/.local/lib/python3.9/site-packages/irrep/bandstructure.py", line 25, in <module>
>     from .readfiles import ParserAbinit, ParserVasp, ParserEspresso, ParserW90, ParserGPAW
>   File "/home/shmr69/.local/lib/python3.9/site-packages/irrep/readfiles.py", line 22, in <module>
>     import h5py
>   File "/home/shmr69/.local/lib/python3.9/site-packages/h5py/__init__.py", line 25, in <module>
>     from . import _errors
>   File "h5py/_errors.pyx", line 1, in init h5py._errors
> ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

A quick search online indicated that this could be related to compatibilty issues with some numpy versions (I'm using version 2.0.2), but from looking at all the dependencies I cannot see any conflicts. Any ideas what might be causing this issue? 
I got a similar error message when trying to import the irrep interface `from irrep.bandstructure import BandStructure`.

Many thanks in advance for the help!

**Comment by shmr69** [comment]
Upgrading to numpy-2.0.2 and h5py-3.12.1 seems to have fixed it. Many thanks for the help!
